version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo
  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo
